from .academicyear import AcademicYear
from .address import Address
from .attendance import Attendance
from .class_academic_year import ClassAcademicAssociation
from .classroom import Classroom
from .event import Event
from .exam_allocated import ExamAllocation
from .exam import Exam
from .fees_payment import FeePayment
from .fees_structure import FeeStructure
from .group import Group
from .leave import Leave
from .marks import Mark
from .question import QuestionPaper
from .scholarship import Scholarship
from .section import Section
from .standard import Standard
from .student_fee import StudentFee
from .student_scholarship_alloc import StudentScholarship
from .student_submission import StudentSubmission
from .studentclass import StudentClass
from .subject_standard_term_resource import SubjectStandardTermResource
from .subject import Subject
from .subjectallocation import SubjectAllocation
from .term import Term
from .timetable import TimeTable
from .token import Apitoken
from .user import User
