"""add forgot password otp table

Revision ID: 5da5cabbee33
Revises: b46c4820f016
Create Date: 2025-07-09 23:16:55.167003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da5cabbee33'
down_revision = 'b46c4820f016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'forgot_password_otp',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('otp', sa.String(length=6), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
