"""Alter exam_allocations table: replace class_academic_id with standard_id and group_id

Revision ID: dbc60d4fdc44
Revises: ecec81eb1dcf
Create Date: 2025-07-07 00:06:40.636343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc60d4fdc44'
down_revision = 'ecec81eb1dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_allocations', sa.Column('standard_id', sa.Integer(), nullable=True))
    op.add_column('exam_allocations', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('exam_allocations_ibfk_1', 'exam_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'exam_allocations', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'exam_allocations', 'standards', ['standard_id'], ['id'])
    op.drop_column('exam_allocations', 'class_academic_id')
    op.alter_column('groups', 'group_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'group_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('exam_allocations', sa.Column('class_academic_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exam_allocations', type_='foreignkey')
    op.drop_constraint(None, 'exam_allocations', type_='foreignkey')
    op.create_foreign_key('exam_allocations_ibfk_1', 'exam_allocations', 'class_academic_associations', ['class_academic_id'], ['id'])
    op.drop_column('exam_allocations', 'group_id')
    op.drop_column('exam_allocations', 'standard_id')
    # ### end Alembic commands ###
