"""models.py creat

Revision ID: ecec81eb1dcf
Revises: 
Create Date: 2025-07-03 15:54:53.376101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecec81eb1dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
